version: '3.9'
services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data:/db/conf/
    env_file:
      - .env
  go_api:
    build: .
    tty: true
    volumes:
      - .:/go/src/api
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    command: air

volumes:
  dbdata: null